POST https://ryhtiapi-test.env.fi/building/api/PermanentIdentifiers/BuildingPermitIdentifier
content-type: application/json

{
  "municipalityNumber": "837",
  "municipalityPermitId": "61360000-5a77-4160-a51f-51eb693f2ea7",
  "permitType": "http://uri.suomi.fi/codelist/rytj/RakennusvalvontaAsianTyyppi/code/01"
}

### Response: 201 Created

{
  "permanentPermitIdentifier": "3000025033",
  "response": "Pysyvä lupatunnus luotu.",
  "created": true
}
