POST https://ryhtiapi-dev.env.fi/building/api/PermanentIdentifiers/ApartmentIdentifier
content-type: application/json

{
  "municipalityNumber": "837",
  "constructionAction": "http://uri.suomi.fi/codelist/rytj/Rakentamistoimenpide/code/01",
  "permanentBuildingId": "900047283A",
  "apartmentKey": "97c48796-365e-411b-a184-c538d3cbf57c",
  "buildingSectionKey": "e5a12706-3023-42dc-b3f8-e3ec44986597",
  "addressNumber": 1,
  "changeType": "http://uri.suomi.fi/codelist/rytj/huoneistonmuutoksenlaji/code/01",
  "apartmentType": "http://uri.suomi.fi/codelist/rytj/Huoneistotyyppi/code/01",
  "apartmentIdentifierLetterSuffix": "A",
  "apartmentNumber": 1,
  "apartmentSubdivisionLetter": "a",
  "numberOfRooms": 5,
  "kitchenType": "http://uri.suomi.fi/codelist/rytj/Keittiotyyppi/code/01",
  "floorArea": 120.5,
  "apartmentEquipment": [
    {
      "apartmentEquipmentKey": "137cf6c1-bd24-4d84-b02d-ce5a764542e1",
      "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/01",
      "numberOfEquipment": 2
    },
    {
      "apartmentEquipmentKey": "ed8b9ffc-575a-48b3-96b8-6a56db8ac705",
      "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/02",
      "numberOfEquipment": 2
    },
    {
      "apartmentEquipmentKey": "64ed8e36-6c56-4b27-9e77-0b1fa058b2a3",
      "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/03",
      "numberOfEquipment": 1
    },
    {
      "apartmentEquipmentKey": "6bc7a86e-9295-4945-a0b2-27678aaf7e00",
      "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/04",
      "numberOfEquipment": 1
    },
    {
      "apartmentEquipmentKey": "262c1c7d-a076-433d-a996-d252c900a15c",
      "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/05",
      "numberOfEquipment": 1
    }
  ]
}

### Response: 201 Created

{
  "permanentApartmentIdentifier": "8000637546",
  "response": "",
  "created": true
}
