POST https://ryhtiapi-dev.env.fi/building/api/PermanentIdentifiers/ApartmentIdentifier
content-type: application/json

{
  "municipalityNumber": "837",
  "constructionAction": "http://uri.suomi.fi/codelist/rytj/Rakentamistoimenpide/code/01",
  "permanentBuildingId": "900047283A",
  "apartmentKey": "27f7432f-6dbd-47a4-89c9-65aa46d92a7f",
  "buildingSectionKey": "8b67cfb3-2777-40ec-ac30-2f86f2267a53",
  "addressNumber": 3,
  "changeType": "http://uri.suomi.fi/codelist/rytj/huoneistonmuutoksenlaji/code/01",
  "apartmentType": "http://uri.suomi.fi/codelist/rytj/Huoneistotyyppi/code/01",
  "apartmentIdentifierLetterSuffix": "C",
  "apartmentNumber": 1,
  "numberOfRooms": 3,
  "kitchenType": "http://uri.suomi.fi/codelist/rytj/Keittiotyyppi/code/01",
  "floorArea": 75.5,
  "apartmentEquipment": [
    {
      "apartmentEquipmentKey": "fd03ba8e-b0f7-4ac5-9434-fa809f867393",
      "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/01",
      "numberOfEquipment": 1
    },
    {
      "apartmentEquipmentKey": "102cd10d-54cf-4795-99b8-290ae97f0309",
      "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/02",
      "numberOfEquipment": 1
    },
    {
      "apartmentEquipmentKey": "7e30b973-d44d-4c9b-8691-320ab9aeafef",
      "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/05",
      "numberOfEquipment": 1
    }
  ]
}

### Response: 201 Created

{
  "permanentApartmentIdentifier": "8000637568",
  "response": "",
  "created": true
}
