POST https://ryhtiapi-dev.env.fi/building/api/BuildingObject/14874692-1714-437e-b089-a797ae9c91d4
content-type: application/json

{
  "buildingObjectIssueKey": "14874692-1714-437e-b089-a797ae9c91d4",
  "municipalityNumber": "837",
  "constructionAction": {
    "constructionActionKey": "a178339d-a6a2-4671-8ff8-af34c14e75cc",
    "constructionActionType": "http://uri.suomi.fi/codelist/rytj/Rakentamistoimenpide/code/09",
    "buildingObjectChange": null,
    "descriptionOfAction": {
      "fin": "Uudisrakennuksen rakentaminen"
    },
    "areaUndergoingChanges": null,
    "reasonForDemolition": null,
    "renovation": false,
    "renovationRate": 0,
    "building": null,
    "finishedBuilding": {
      "buildingKey": "30d3debe-a1d7-488e-839b-567a0b7f02ee",
      "permanentBuildingIdentifier": "900047283A",
      "temporary": false,
      "demolitionDeadline": null,
      "numberOfStoreys": 2,
      "buildingSection": [
        {
          "buildingSectionKey": "e5a12706-3023-42dc-b3f8-e3ec44986597",
          "lifeCycleState": "http://uri.suomi.fi/codelist/rakrek/rakelinvaih/code/03",
          "completionDate": "2024-12-31",
          "partitionReason": "http://uri.suomi.fi/codelist/rytj/rak-osittelun-laji/code/2",
          "materialData": {
            "constructionMethod": "http://uri.suomi.fi/codelist/vtj/Rake_runkotapa/code/01",
            "buildingMaterialOfLoadBearingStructures": [
              {
                "buildingMaterialOfLoadBearingStructuresKey": "33e65d9b-0fb3-4255-8d4d-c67848fc36a0",
                "buildingMaterialOfLoadBearingStructuresType": "http://uri.suomi.fi/codelist/rytj/kantavanrakenteenrakennusaine/code/01",
                "isPrimary": true
              }
            ],
            "facadeMaterial": [
              {
                "facadeMaterialKey": "5b74e021-6561-42ec-a0b3-7781d2151e0e",
                "facadeMaterialType": "http://uri.suomi.fi/codelist/rytj/julkisivunrakennusaine/code/01",
                "isPrimary": true
              }
            ],
            "fireClass": "http://uri.suomi.fi/codelist/rytj/Paloluokka/code/00",
            "wideBodiedBuilding": false,
            "reusableMaterialAmount": 100
          },
          "energyData": {
            "energyDataKey": "65bd7dbd-7f6f-478c-8b9a-b84d4352478d",
            "energyEfficiencyRating": "http://uri.suomi.fi/codelist/rytj/Energiatehokkuusluokka/code/01",
            "computationalEnergyEfficiencyComparand": 150,
            "heatingMethod": [
              {
                "heatingMethodKey": "f6da7532-650c-4d1f-9ad2-f2ee9aa63f32",
                "heatingMethodType": "http://uri.suomi.fi/codelist/rytj/lammitystapa/code/01",
                "isPrimary": true
              }
            ],
            "heatingEnergySource": [
              {
                "heatingEnergySourceKey": "093430bc-6361-4cd5-8ecb-f334e3639410",
                "heatingEnergySourceType": "http://uri.suomi.fi/codelist/rytj/lammitysenergianlahde/code/01",
                "isPrimary": true
              }
            ],
            "coolingMethod": [
              {
                "coolingMethodKey": "9e0b4fe3-7869-499d-9779-bd86e79d96c8",
                "coolingMethodType": "http://uri.suomi.fi/codelist/rytj/jaahdytystapa/code/01",
                "isPrimary": true
              }
            ],
            "coolingEnergySource": [
              {
                "coolingEnergySourceKey": "83ec5096-e1b4-49a9-9c3e-6823034ee55f",
                "coolingEnergySourceType": "http://uri.suomi.fi/codelist/rytj/jaahdytys/code/01",
                "isPrimary": true
              }
            ],
            "electricalEnergySource": [
              {
                "electricalEnergySourceKey": "3b1e5b27-2060-456c-a13b-3e15cbbab6aa",
                "electricalEnergySourceType": "http://uri.suomi.fi/codelist/rytj/sahkoenergianlahde/code/01",
                "isPrimary": true
              }
            ],
            "netHeatedArea": 180,
            "heatedVolume": 540,
            "attachment": [
              {
                "attachmentType": "http://uri.suomi.fi/codelist/rytj/ravaasiaki/code/01",
                "attachmentDocumentKey": "f5aa23d9-072e-420e-8c39-147e341ddd01",
                "documentIdentifier": "ENERGY-1781613597396",
                "name": {
                  "fin": "Energiatodistus"
                },
                "personalDataContent": "http://uri.suomi.fi/codelist/rytj/henkilotietosisalto/code/1",
                "categoryOfPublicity": "http://uri.suomi.fi/codelist/rytj/julkisuus/code/1",
                "accessibility": true,
                "retentionTime": "http://uri.suomi.fi/codelist/rytj/sailytysaika/code/01",
                "confirmationDate": "2024-12-01",
                "languages": [
                  "http://uri.suomi.fi/codelist/rytj/ryhtikielet/code/fi"
                ],
                "fileKey": "9a28e13e-dde6-4906-9e39-99c39e4725f8",
                "documentDate": "2026-06-16"
              }
            ],
            "calculatoryDeliveredEnergyUsage": {
              "calculatoryDeliveredEnergyUsageKey": "a4ce2c06-25f5-4612-b264-b4e8c04533a6",
              "deliveredEnergyType": "http://uri.suomi.fi/codelist/rytj/ostoenergia/code/01",
              "energyAmountYearly": 5000
            },
            "energyRatingSubindex": "http://uri.suomi.fi/codelist/rytj/energialuokkaAlaindeksi/code/01"
          },
          "apartment": [
            {
              "apartmentKey": "97c48796-365e-411b-a184-c538d3cbf57c",
              "lifeCycleState": "http://uri.suomi.fi/codelist/rytj/huon-elinkaaren-vaihe/code/4",
              "apartmentEquipment": [
                {
                  "apartmentEquipmentKey": "262c1c7d-a076-433d-a996-d252c900a15c",
                  "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/05",
                  "numberOfEquipment": 1
                },
                {
                  "apartmentEquipmentKey": "ed8b9ffc-575a-48b3-96b8-6a56db8ac705",
                  "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/02",
                  "numberOfEquipment": 2
                },
                {
                  "apartmentEquipmentKey": "64ed8e36-6c56-4b27-9e77-0b1fa058b2a3",
                  "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/03",
                  "numberOfEquipment": 1
                },
                {
                  "apartmentEquipmentKey": "6bc7a86e-9295-4945-a0b2-27678aaf7e00",
                  "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/04",
                  "numberOfEquipment": 1
                },
                {
                  "apartmentEquipmentKey": "137cf6c1-bd24-4d84-b02d-ce5a764542e1",
                  "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/01",
                  "numberOfEquipment": 2
                }
              ],
              "apartmentIdentifier": "8000637546",
              "apartmentType": "http://uri.suomi.fi/codelist/rytj/Huoneistotyyppi/code/01",
              "floorArea": 120.5,
              "numberOfRooms": 5,
              "kitchenType": "http://uri.suomi.fi/codelist/rytj/Keittiotyyppi/code/01",
              "addressNumber": 1,
              "apartmentIdentifierLetterSuffix": "A",
              "apartmentSubdivisionLetter": "a",
              "apartmentNumber": 1,
              "apartmentChangeType": "http://uri.suomi.fi/codelist/rytj/huoneistonmuutoksenlaji/code/02"
            },
            {
              "apartmentKey": "afc84346-f070-4259-8725-ef8d7d53581d",
              "lifeCycleState": "http://uri.suomi.fi/codelist/rytj/huon-elinkaaren-vaihe/code/4",
              "apartmentEquipment": [],
              "apartmentIdentifier": "8000637557",
              "apartmentType": "http://uri.suomi.fi/codelist/rytj/Huoneistotyyppi/code/02",
              "floorArea": 20,
              "numberOfRooms": 1,
              "kitchenType": "http://uri.suomi.fi/codelist/rytj/Keittiotyyppi/code/02",
              "addressNumber": 2,
              "apartmentIdentifierLetterSuffix": "A",
              "apartmentSubdivisionLetter": "a",
              "apartmentNumber": 2,
              "apartmentChangeType": "http://uri.suomi.fi/codelist/rytj/huoneistonmuutoksenlaji/code/02"
            }
          ],
          "interiorData": {
            "floorArea": 300,
            "atticArea": 30,
            "basementArea": 50
          },
          "exteriorData": {
            "numberOfStoreys": 2,
            "height": 5,
            "flightObstacle": false,
            "shape": {
              "srid": "3067",
              "geometry": {
                "type": "Polygon",
                "coordinates": [
                  [
                    [
                      386023,
                      6672105
                    ],
                    [
                      386033,
                      6672105
                    ],
                    [
                      386033,
                      6672115
                    ],
                    [
                      386023,
                      6672115
                    ],
                    [
                      386023,
                      6672105
                    ]
                  ]
                ]
              }
            },
            "relationToGroundLevel": "http://uri.suomi.fi/codelist/rytj/Suhde_pintaan/code/01",
            "volume": 750,
            "grossFloorArea": 320,
            "permittedBuildingArea": 300,
            "totalArea": 350
          },
          "usageData": {
            "commissioningDate": "2024-12-31",
            "usageStatus": "http://uri.suomi.fi/codelist/vtj/rake_kaytossaolotilanne/code/01",
            "purpose": [
              {
                "purposeKey": "edcc5608-dff2-492a-bcef-b8f46b9c006d",
                "type": "http://uri.suomi.fi/codelist/jhs/rakennus_1_20180712/code/0110",
                "isPrimary": true
              }
            ],
            "usefulFloorArea": 180,
            "intendedWorkingLife": 50,
            "plannedUserCount": 4
          },
          "protectionMethod": "http://uri.suomi.fi/codelist/rytj/suojtapa/code/01",
          "cultureHistoricalSignificance": "http://uri.suomi.fi/codelist/rakrek/kulthistmer/code/1"
        },
        {
          "buildingSectionKey": "8b67cfb3-2777-40ec-ac30-2f86f2267a53",
          "lifeCycleState": "http://uri.suomi.fi/codelist/rakrek/rakelinvaih/code/03",
          "completionDate": "2024-12-31",
          "partitionReason": "http://uri.suomi.fi/codelist/rytj/rak-osittelun-laji/code/2",
          "materialData": {
            "constructionMethod": "http://uri.suomi.fi/codelist/vtj/Rake_runkotapa/code/01",
            "buildingMaterialOfLoadBearingStructures": [
              {
                "buildingMaterialOfLoadBearingStructuresKey": "5b094692-ac5c-4678-8ddd-c2d0041f4ab4",
                "buildingMaterialOfLoadBearingStructuresType": "http://uri.suomi.fi/codelist/rytj/kantavanrakenteenrakennusaine/code/01",
                "isPrimary": true
              }
            ],
            "facadeMaterial": [
              {
                "facadeMaterialKey": "4cde8885-bea7-4275-b84e-ccf9cb48a849",
                "facadeMaterialType": "http://uri.suomi.fi/codelist/rytj/julkisivunrakennusaine/code/01",
                "isPrimary": true
              }
            ],
            "wideBodiedBuilding": false
          },
          "apartment": [
            {
              "apartmentKey": "27f7432f-6dbd-47a4-89c9-65aa46d92a7f",
              "lifeCycleState": "http://uri.suomi.fi/codelist/rytj/huon-elinkaaren-vaihe/code/4",
              "apartmentEquipment": [
                {
                  "apartmentEquipmentKey": "102cd10d-54cf-4795-99b8-290ae97f0309",
                  "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/02",
                  "numberOfEquipment": 1
                },
                {
                  "apartmentEquipmentKey": "7e30b973-d44d-4c9b-8691-320ab9aeafef",
                  "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/05",
                  "numberOfEquipment": 1
                },
                {
                  "apartmentEquipmentKey": "fd03ba8e-b0f7-4ac5-9434-fa809f867393",
                  "apartmentEquipmentType": "http://uri.suomi.fi/codelist/rytj/HuoneistoVaruste/code/01",
                  "numberOfEquipment": 1
                }
              ],
              "apartmentIdentifier": "8000637568",
              "apartmentType": "http://uri.suomi.fi/codelist/rytj/Huoneistotyyppi/code/01",
              "floorArea": 75.5,
              "numberOfRooms": 3,
              "kitchenType": "http://uri.suomi.fi/codelist/rytj/Keittiotyyppi/code/01",
              "addressNumber": 2,
              "apartmentIdentifierLetterSuffix": "C",
              "apartmentNumber": 1,
              "apartmentChangeType": "http://uri.suomi.fi/codelist/rytj/huoneistonmuutoksenlaji/code/02"
            }
          ],
          "interiorData": {
            "floorArea": 100
          },
          "exteriorData": {
            "numberOfStoreys": 1,
            "volume": 360,
            "grossFloorArea": 120,
            "permittedBuildingArea": 120,
            "totalArea": 120
          },
          "usageData": {
            "purpose": [
              {
                "purposeKey": "a7b2b9e0-6824-4b3a-9ccd-78ed444fd979",
                "type": "http://uri.suomi.fi/codelist/jhs/rakennus_1_20180712/code/0112",
                "isPrimary": true
              }
            ],
            "intendedWorkingLife": 50,
            "plannedUserCount": 4
          }
        }
      ],
      "mainPurpose": "http://uri.suomi.fi/codelist/jhs/rakennus_1_20180712/code/0112",
      "buildingObjectType": "http://uri.suomi.fi/codelist/rytj/rakkohteen-tiedon-laji/code/2",
      "location": {
        "buildingObjectLocationDataKey": "f5ba9e06-f456-4e23-a04d-458bad54ead3",
        "votingDistrictNumber": "001",
        "pointLocation": {
          "srid": "3067",
          "geometry": {
            "type": "Point",
            "coordinates": [
              337367,
              6840313
            ]
          }
        },
        "geometry": []
      },
      "administrativeLocationUnit": {
        "administrativeLocationUnitKey": "c3738382-b014-41ee-9e3e-9c889b383fd7",
        "unitIdentifier": null,
        "propertyIdentifier": "83770500010146",
        "unseparatedParcelIdentifier": null
      },
      "decisionAdministrativeLocationUnit": null,
      "buildingObjectOwner": [
        {
          "buildingObjectOwnerKey": "9a981b97-1715-43ba-a572-3d98be520d68",
          "ownerOperator": {
            "personalIdentityCode": "010170-999R",
            "isPerson": true,
            "firstName": "Tero Petteri",
            "familyName": "Testaaja",
            "operatorAddress": [
              {
                "addressKey": "e501be67-0caa-41ba-9f41-14449bad8e74",
                "apartmentIdentifierLetterSuffix": "B",
                "apartmentIdentifierNumber": 2,
                "apartmentIdentifierSubdivisionLetter": "a",
                "postalAddress": {
                  "fin": "Kivinokka 435",
                  "swe": "Stenudden 435"
                },
                "contactAddressType": "http://uri.suomi.fi/codelist/rytj/yhteysosoitteenLaji/code/05",
                "source": "http://uri.suomi.fi/codelist/rytj/tietolahde/code/01",
                "addressName": {
                  "fin": "Kivinokka",
                  "swe": "Stenudden"
                },
                "numberPartOfAddressNumber": 435,
                "postalCode": "00810"
              }
            ],
            "languageCode": "http://uri.suomi.fi/codelist/interoperabilityplatform/languagecodes/code/fi",
            "nationalityCode": "http://uri.suomi.fi/codelist/jhs/valtio_1_20120101/code/246"
          },
          "differentOwner": true,
          "tenureStatus": {
            "fin": "Omistaa"
          },
          "ownerType": "http://uri.suomi.fi/codelist/rytj/Omistajalaji/code/01"
        },
        {
          "buildingObjectOwnerKey": "8cd72c06-5cc5-458c-96d5-387bdae1cebf",
          "ownerOperator": {
            "personalIdentityCode": "010170-999R",
            "isPerson": true,
            "firstName": "Tero Petteri",
            "familyName": "Testaaja",
            "operatorAddress": [
              {
                "addressKey": "e501be67-0caa-41ba-9f41-14449bad8e74",
                "apartmentIdentifierLetterSuffix": "B",
                "apartmentIdentifierNumber": 2,
                "apartmentIdentifierSubdivisionLetter": "a",
                "postalAddress": {
                  "fin": "Kivinokka 435",
                  "swe": "Stenudden 435"
                },
                "contactAddressType": "http://uri.suomi.fi/codelist/rytj/yhteysosoitteenLaji/code/05",
                "source": "http://uri.suomi.fi/codelist/rytj/tietolahde/code/01",
                "addressName": {
                  "fin": "Kivinokka",
                  "swe": "Stenudden"
                },
                "numberPartOfAddressNumber": 435,
                "postalCode": "00810"
              }
            ],
            "languageCode": "http://uri.suomi.fi/codelist/interoperabilityplatform/languagecodes/code/fi",
            "nationalityCode": "http://uri.suomi.fi/codelist/jhs/valtio_1_20120101/code/246"
          },
          "differentOwner": true,
          "tenureStatus": {
            "fin": "Omistaa"
          },
          "ownerType": "http://uri.suomi.fi/codelist/rytj/Omistajalaji/code/01"
        }
      ],
      "address": [
        {
          "addressKey": "ce16a6a9-98ba-4091-b272-9af4f80e4a12",
          "addressNumber": 1,
          "addressName": {
            "fin": "Testikatu"
          },
          "numberPartOfAddressNumber": 1,
          "subdivisionLetterOfAddressNumber": "a",
          "postalCode": "33100",
          "numberPartOfAddressNumber2": 1,
          "subdivisionLetterOfAddressNumber2": "b"
        },
        {
          "addressKey": "2973bbc4-12c9-45b6-90ed-545e187653bf",
          "addressNumber": 2,
          "addressName": {
            "fin": "Uusikatu"
          },
          "numberPartOfAddressNumber": 2,
          "postalCode": "33100",
          "location": {
            "srid": "3067",
            "geometry": {
              "type": "Point",
              "coordinates": [
                386025,
                6672107
              ]
            }
          }
        }
      ],
      "name": null,
      "description": null,
      "renovationDate": null,
      "buildingProductList": null,
      "climateReport": null,
      "chargingPoint": null,
      "bikespaceCount": 10
    },
    "structure": null,
    "areaToBeBuiltForSpecificActivities": null,
    "startDate": null,
    "completionDate": "2024-12-31",
    "commissioningDate": null,
    "finishedAreaToBeBuiltForSpecificActivities": null,
    "statusOfConstructionAction": "http://uri.suomi.fi/codelist/rytj/rakkohteen-toimenpiteen-tila/code/5",
    "fullyApprovedForUse": null,
    "businessConstruction": false,
    "changeType": null,
    "dvvPermitIdentifier": null,
    "expiryDate": null
  },
  "buildingSite": {
    "buildingSiteKey": "75286458-7371-4e0b-a229-b8d1f7d99dc2",
    "area": 1000,
    "stormWaterTreatmentType": "http://uri.suomi.fi/codelist/rytj/hulevedenkasittely/code/01",
    "spatialPlan": null,
    "statusOfPlan": "http://uri.suomi.fi/codelist/vtj/Rake_kaava/code/01",
    "name": null,
    "description": null,
    "geometry": {
      "srid": "3067",
      "geometry": {
        "type": "Point",
        "coordinates": [
          337367,
          6840313
        ]
      }
    },
    "buildingSiteAddress": [
      {
        "addressKey": "47811773-ab11-4ed1-8597-4f7c4ced365b",
        "addressName": {
          "fin": "Rakennustie"
        },
        "numberPartOfAddressNumber": null,
        "subdivisionLetterOfAddressNumber": null,
        "postalCode": "33100",
        "location": null,
        "addressNumber": 1,
        "numberPartOfAddressNumber2": null,
        "subdivisionLetterOfAddressNumber2": null
      }
    ],
    "tenure": "http://uri.suomi.fi/codelist/rytj/RakennuspaikanHallintaperuste/code/1"
  }
}

### Response: 201 Created
