POST https://ryhtiapi-dev.env.fi/building/api/PermanentIdentifiers/ApartmentIdentifier
content-type: application/json

{
  "municipalityNumber": "837",
  "permanentPermitId": "300004595K",
  "dvvCaseIdentifier": "83752555-09240011010",
  "constructionAction": "http://uri.suomi.fi/codelist/rytj/Rakentamistoimenpide/code/01",
  "permanentBuildingId": "900047044L",
  "addressNumber": 1,
  "changeType": "http://uri.suomi.fi/codelist/rytj/huoneistonmuutoksenlaji/code/01",
  "apartmentType": "http://uri.suomi.fi/codelist/rytj/Huoneistotyyppi/code/01",
  "apartmentIdentifierLetterSuffix": "A",
  "apartmentNumber": 1,
  "apartmentSubdivisionLetter": "a",
  "numberOfRooms": 4,
  "kitchenType": "http://uri.suomi.fi/codelist/rytj/Keittiotyyppi/code/02",
  "floorArea": 120
}

### Response: 201 Created

{
  "permanentApartmentIdentifier": "8000636937",
  "response": "",
  "created": true
}
