POST https://ryhtiapi-dev.env.fi/building/api/file?municipalityId=837
content-type: multipart/form-data; boundary=--------------------------02cc8fccbb1c38cb8b139dd6

### Response: 201 Created

2284a033-882c-488c-b021-d479133e0723
