POST https://ryhtiapi-dev.env.fi/building/api/PermanentIdentifiers/BuildingPermitIdentifier
content-type: application/json

{
  "municipalityNumber": "837",
  "municipalityPermitId": "d9a72355-866c-4939-86f4-6d667559af7c",
  "permitType": "http://uri.suomi.fi/codelist/rytj/RakennusvalvontaAsianTyyppi/code/01"
}

### Response: 201 Created

{
  "permanentPermitIdentifier": "3000043323",
  "response": "Pysyvä lupatunnus luotu.",
  "created": true
}
