POST https://ryhtiapi-test.env.fi/building/api/PermanentIdentifiers/BuildingPermitIdentifier
content-type: application/json

{
  "municipalityNumber": "837",
  "municipalityPermitId": "8820be53-77b1-4662-b187-810befc908c0",
  "permitType": "http://uri.suomi.fi/codelist/rytj/RakennusvalvontaAsianTyyppi/code/02"
}

### Response: 201 Created

{
  "permanentPermitIdentifier": "300002386A",
  "response": "Pysyvä lupatunnus luotu.",
  "created": true
}
