PUT https://ryhtiapi-test.env.fi/building/api/DemolitionPermit/300002386A
content-type: application/json

{
  "demolitionDecision": {
    "engagingParty": [
      {
        "engagingPartyKey": "ea0a93af-ba17-4c4e-b905-6b28b8a783f7",
        "personalIdentityCode": "010170-999R",
        "isPerson": true,
        "firstName": "Matti",
        "familyName": "Virtanen"
      }
    ],
    "decisionDocument": {
      "attachmentType": "http://uri.suomi.fi/codelist/rytj/ravaasiaki/code/01",
      "attachmentDocumentKey": "99698626-63c6-4972-a02d-f64d4dcaf169",
      "documentIdentifier": "LUP-2024-001",
      "name": {
        "fin": "Rakennuslupapäätös",
        "swe": "Bygglovsbeslut",
        "smn": "Rakennuslupapäätös",
        "sms": "Rakennuslupapäätös",
        "sme": "Rakennuslupapäätös",
        "eng": "Building Permit Decision"
      },
      "personalDataContent": "http://uri.suomi.fi/codelist/rytj/henkilotietosisalto/code/3",
      "categoryOfPublicity": "http://uri.suomi.fi/codelist/rytj/julkisuus/code/1",
      "accessibility": true,
      "retentionTime": "http://uri.suomi.fi/codelist/rytj/sailytysaika/code/01",
      "confirmationDate": "2023-03-29",
      "languages": [
        "http://uri.suomi.fi/codelist/rytj/ryhtikielet/code/fi"
      ],
      "fileKey": "86d78e7c-44cb-45e1-9f6a-04f6f01ef260",
      "documentDate": "2023-03-16"
    },
    "demolitionPermitDecisionKey": "9c0122b5-0f1d-4d88-b0dc-328235112997",
    "constructionToBeStartedBy": "2026-06-01",
    "constructionToBeCompletedBy": "2026-12-31",
    "acceptedDeviation": [
      {
        "acceptedDeviationKey": "c009023e-4787-40c6-9f95-95052e5c3e9b",
        "deviationType": "http://uri.suomi.fi/codelist/rytj/PoikkeamisenLaji/code/01",
        "contentOfDeviation": {
          "fin": "Poikkeamisen sisältö",
          "swe": "Avvikelsens innehåll",
          "smn": "Poikkeamisen sisältö",
          "sms": "Poikkeamisen sisältö",
          "sme": "Poikkeamisen sisältö",
          "eng": "Content of deviation"
        }
      }
    ],
    "permitRegulation": [
      {
        "permitRegulationKey": "e55d3c13-9fcd-44f2-bd0f-4840bf4b1e1f",
        "permitRegulationType": "http://uri.suomi.fi/codelist/rytj/Lupamaarayshierarkinen/code/M01",
        "textOfPermitRegulation": {
          "fin": "Lupamääräyksen teksti",
          "swe": "Texten för lovvillkoret",
          "smn": "Lupamääräyksen teksti",
          "sms": "Lupamääräyksen teksti",
          "sme": "Lupamääräyksen teksti",
          "eng": "Text of permit regulation"
        }
      }
    ],
    "lifeCycleState": "http://uri.suomi.fi/codelist/rytj/paatoksen-elinkaaren-tila/code/11",
    "decisionDate": "2026-05-27",
    "dateOfDecision": "2026-05-27",
    "dateOfValidityOfDecision": "2026-05-27",
    "decisionArticle": "§ 125",
    "publicNoticeDate": "2026-05-27",
    "decisionText": {
      "fin": "Lupa myönnetään hakemuksen mukaisesti",
      "swe": "Tillstånd beviljas enligt ansökan",
      "smn": "Lupa myönnetään hakemuksen mukaisesti",
      "sms": "Lupa myönnetään hakemuksen mukaisesti",
      "sme": "Lupa myönnetään hakemuksen mukaisesti",
      "eng": "Permit granted as applied"
    },
    "guidingStatute": [
      {
        "guidingStatuteKey": "89151bb1-3186-4839-aae1-6b0868fffe6f",
        "statuteName": {
          "fin": "Maankäyttö- ja rakennuslaki",
          "swe": "Mark- och bygglag",
          "smn": "Maankäyttö- ja rakennuslaki",
          "sms": "Maankäyttö- ja rakennuslaki",
          "sme": "Maankäyttö- ja rakennuslaki",
          "eng": "Land Use and Building Act"
        },
        "statuteCollectionNumber": 2023,
        "statuteCollectionYear": 2023,
        "chapter": 0,
        "section": 0,
        "subSection": 0,
        "paragraph": 0,
        "subParagraph": "§ 125 a"
      }
    ],
    "relatedPermit": [],
    "decisionMakerType": "http://uri.suomi.fi/codelist/rytj/PaatoksenTekija/code/01",
    "decisionMakerFirstName": "Viranomainen",
    "decisionMakerName": {
      "fin": "Rakennusvalvontaviranomainen",
      "swe": "Byggnadstillsynsmyndigheten",
      "smn": "Rakennusvalvontaviranomainen",
      "sms": "Rakennusvalvontaviranomainen",
      "sme": "Rakennusvalvontaviranomainen",
      "eng": "Building Control Authority"
    },
    "relatedApplication": "8e93dfe1-01da-411d-bc08-1b93c5eaeb47"
  },
  "extensionDecision": [],
  "changePermit": [],
  "constructionAction": [
    {
      "building": {
        "buildingKey": "18fb5bf3-5736-4515-844a-9cd27acd2aa7",
        "permanentBuildingIdentifier": "9000437157",
        "numberOfStoreys": 2,
        "buildingSection": [],
        "mainPurpose": "http://uri.suomi.fi/codelist/jhs/rakennus_1_20180712/code/0110",
        "buildingObjectType": "http://uri.suomi.fi/codelist/rytj/rakkohteen-tiedon-laji/code/1",
        "location": {
          "buildingObjectLocationDataKey": "bce9b126-f278-49ac-82cf-9eecbeff21ad",
          "votingDistrictNumber": "001",
          "pointLocation": {
            "srid": "3067",
            "geometry": {
              "type": "Point",
              "coordinates": [
                336976,
                6840804
              ]
            }
          },
          "geometry": []
        },
        "administrativeLocationUnit": {
          "administrativeLocationUnitKey": "0a628ec7-c669-4fd3-8f0e-2e49becca468",
          "propertyIdentifier": "83770500010146"
        },
        "decisionAdministrativeLocationUnit": {
          "administrativeLocationUnitKey": "97b6967a-5670-4256-be1a-724999a2db7b",
          "propertyIdentifier": "83770500010146"
        },
        "buildingObjectOwner": [
          {
            "buildingObjectOwnerKey": "20e143d7-69c6-4eb9-8f5c-f0443e99cc72",
            "ownerOperator": {
              "personalIdentityCode": "010170-999R",
              "isPerson": true,
              "firstName": "Tero Petteri",
              "familyName": "Testaaja",
              "operatorAddress": [
                {
                  "addressKey": "6cb137d2-eb65-4e0f-ab68-ac242c59eba1",
                  "apartmentIdentifierLetterSuffix": "B",
                  "apartmentIdentifierNumber": 2,
                  "apartmentIdentifierSubdivisionLetter": "a",
                  "postalAddress": {
                    "fin": "Kivinokka 435",
                    "swe": "Stenudden 435"
                  },
                  "contactAddressType": "http://uri.suomi.fi/codelist/rytj/yhteysosoitteenLaji/code/05",
                  "source": "http://uri.suomi.fi/codelist/rytj/tietolahde/code/01",
                  "addressName": {
                    "fin": "Kivinokka",
                    "swe": "Stenudden"
                  },
                  "numberPartOfAddressNumber": 435,
                  "postalCode": "00810"
                },
                {
                  "addressKey": "264c74dd-6bbb-4231-89fb-aefe846faa38",
                  "postalAddress": {
                    "fin": "Koukkujärventie"
                  },
                  "contactAddressType": "http://uri.suomi.fi/codelist/rytj/yhteysosoitteenLaji/code/01",
                  "source": "http://uri.suomi.fi/codelist/rytj/tietolahde/code/01",
                  "addressName": {
                    "fin": "Koukkujärventie 420"
                  },
                  "numberPartOfAddressNumber": 420,
                  "postalCode": "37100"
                }
              ],
              "languageCode": "http://uri.suomi.fi/codelist/interoperabilityplatform/languagecodes/code/fi",
              "nationalityCode": "http://uri.suomi.fi/codelist/jhs/valtio_1_20120101/code/246"
            },
            "differentOwner": true,
            "tenureStatus": {
              "fin": "Hallintaperuste 1",
              "swe": "Besittningsförhållande 1",
              "smn": "Hallintaperuste 1",
              "sms": "Hallintaperuste 1",
              "sme": "Hallintaperuste 1",
              "eng": "TenureStatus 1"
            },
            "ownerType": "http://uri.suomi.fi/codelist/rytj/Omistajalaji/code/01"
          }
        ],
        "address": [
          {
            "addressKey": "1d552537-d0e3-4781-afb2-fbcf6204755e",
            "addressNumber": 1,
            "addressName": {
              "fin": "Vuokkolantie",
              "swe": "Vuokkolovägen"
            },
            "numberPartOfAddressNumber": 55,
            "subdivisionLetterOfAddressNumber": "a",
            "postalCode": "33100",
            "location": {
              "srid": "3067",
              "geometry": {
                "type": "Point",
                "coordinates": [
                  337489,
                  6840116
                ]
              }
            }
          },
          {
            "addressKey": "a8b27b01-9861-4610-8d29-5583e526d897",
            "addressNumber": 2,
            "addressName": {
              "fin": "Vuokkolantie",
              "swe": "Vuokkolovägen"
            },
            "numberPartOfAddressNumber": 59,
            "subdivisionLetterOfAddressNumber": "c",
            "postalCode": "33100",
            "location": {
              "srid": "3067",
              "geometry": {
                "type": "Point",
                "coordinates": [
                  336976,
                  6840804
                ]
              }
            }
          }
        ],
        "description": {
          "fin": "Asuinkerrostalo, jossa on useita huoneistoja"
        }
      },
      "constructionActionKey": "bdaf6dfc-86f0-4677-9605-df0a4bcd9ed9",
      "constructionActionType": "http://uri.suomi.fi/codelist/rytj/Rakentamistoimenpide/code/05",
      "descriptionOfAction": {
        "fin": "Rakentamistoimenpiteen kuvaus",
        "swe": "Beskrivning av byggåtgärd",
        "smn": "Rakentamistoimenpiteen kuvaus",
        "sms": "Rakentamistoimenpiteen kuvaus",
        "sme": "Rakentamistoimenpiteen kuvaus",
        "eng": "Description of construction action"
      },
      "reasonForDemolition": "http://uri.suomi.fi/codelist/rytj/PurkamisenSyy/code/04",
      "renovation": false,
      "renovationRate": 0,
      "statusOfConstructionAction": "http://uri.suomi.fi/codelist/rytj/rakkohteen-toimenpiteen-tila/code/5",
      "businessConstruction": true,
      "completionDate": "2026-05-27"
    }
  ],
  "attachment": [
    {
      "attachmentType": "http://uri.suomi.fi/codelist/rytj/ravaasiaki/code/01",
      "attachmentDocumentKey": "c5b4c42e-e86b-484a-abd7-f3c08d73ba70",
      "documentIdentifier": "LUP-2024-001",
      "name": {
        "fin": "Liite",
        "swe": "Bilaga",
        "smn": "Liite",
        "sms": "Liite",
        "sme": "Liite",
        "eng": "Attachment"
      },
      "personalDataContent": "http://uri.suomi.fi/codelist/rytj/henkilotietosisalto/code/3",
      "categoryOfPublicity": "http://uri.suomi.fi/codelist/rytj/julkisuus/code/1",
      "accessibility": true,
      "retentionTime": "http://uri.suomi.fi/codelist/rytj/sailytysaika/code/01",
      "confirmationDate": "2023-03-29",
      "languages": [
        "http://uri.suomi.fi/codelist/rytj/ryhtikielet/code/fi"
      ],
      "fileKey": "86d78e7c-44cb-45e1-9f6a-04f6f01ef260",
      "documentDate": "2023-03-17"
    }
  ],
  "constructionProject": {
    "constructionProjectKey": "c25da6c7-00df-49f2-be07-b33af8f6e969",
    "descriptionOfConstructionProject": {
      "fin": "Rakennushankkeen kuvaus",
      "swe": "Beskrivning av byggprojekt",
      "smn": "Rakennushankkeen kuvaus",
      "sms": "Rakennushankkeen kuvaus",
      "sme": "Rakennushankkeen kuvaus",
      "eng": "Description of construction project"
    },
    "startDate": "2026-05-27",
    "planner": [],
    "foreman": [],
    "inspection": [],
    "endDate": "2026-05-27"
  },
  "permanentPermitIdentifier": "300002386A",
  "demolitionPermitApplication": [
    {
      "demolitionPermitApplicationKey": "8e93dfe1-01da-411d-bc08-1b93c5eaeb47",
      "lifeCycleState": "http://uri.suomi.fi/codelist/rytj/lupahak-elinkaaren-tila/code/2",
      "applicationContent": "Rakennuslupahakemus rakennuksen muutostöitä varten",
      "dateOfReception": "2026-05-27",
      "callForDeviation": []
    }
  ],
  "buildingSite": {
    "buildingSiteKey": "7f9d5b14-045d-4c66-b030-3a3ae47efd5b",
    "area": 3,
    "stormWaterTreatmentType": "http://uri.suomi.fi/codelist/rytj/hulevedenkasittely/code/01",
    "buildingSiteAddress": [
      {
        "addressKey": "4c7e9561-a571-4f70-a792-7c6893e47228",
        "addressNumber": 1,
        "addressName": {
          "fin": "Koulutie",
          "swe": "Skolgatan"
        },
        "numberPartOfAddressNumber": 0,
        "subdivisionLetterOfAddressNumber": "a",
        "postalCode": "42700",
        "location": {
          "srid": "3067",
          "geometry": {
            "type": "Point",
            "coordinates": [
              386023.53933660605,
              6672105.533725229
            ]
          }
        },
        "numberPartOfAddressNumber2": 3,
        "subdivisionLetterOfAddressNumber2": "a"
      }
    ],
    "spatialPlan": "6706100",
    "statusOfPlan": "http://uri.suomi.fi/codelist/vtj/Rake_kaava/code/01",
    "tenure": "http://uri.suomi.fi/codelist/rytj/RakennuspaikanHallintaperuste/code/1",
    "geometry": {
      "srid": "3067",
      "geometry": {
        "type": "Point",
        "coordinates": [
          386023.53933660605,
          6672105.533725229
        ]
      }
    }
  },
  "dateOfInitiation": "2026-05-27",
  "lifeCycleState": "http://uri.suomi.fi/codelist/rytj/rakvalv-asian-elinkaaren-tila/code/4",
  "municipalityNumber": "837",
  "updateType": "http://uri.suomi.fi/codelist/rytj/paivityksenlaji/code/04",
  "updateDescription": {
    "fin": "Purkamisen loppukatselmus, rakennus purettu kokonaan",
    "eng": "Final inspection, building fully demolished"
  }
}

### Response: 200 OK

300002386A Deletion of building 9000437157 from the Population Information System succeeded
